#!/bin/bash
# Make sure worker uses production Supabase
export NEXT_PUBLIC_SUPABASE_URL="https://maopxuzkzncglajxlgdh.supabase.co"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hb3B4dXp6em5jZ2xhanhsZ2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk5NzQyOTcsImV4cCI6MjA0NTU1MDI5N30.JdMZhPmIICVmm2KbNxkSRoU75C2IBPVG-ZQZvJ7V0QQ"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hb3B4dXp6em5jZ2xhanhsZ2RoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyOTk3NDI5NywiZXhwIjoyMDQ1NTUwMjk3fQ.z3vvh7H5q7Qg3KUF3vjIBKBJbmJMACNWFq-q7sESrBU"

npm run worker
